POST http://localhost:3000/common-api/register
Content-Type: application/json

{
    "firstName":"Agent",
    "lastName":"47",
    "email":"A47@gmail.com",
    "password":"hitman",
    "role":"user"
}

###
POST http://localhost:3000/common-api/login
Content-Type: application/json

{
    "email":"johndoe@gmail.com",
    "password":"password123"
}

###
GET http://localhost:3000/user-api/articles

###
PUT http://localhost:3000/user-api/comment/articleid/69842dfa5db940c83c8a8487
Content-Type: application/json

{
    "comment":"Great article! Really enjoyed reading it."
}

//--------------------USER API END--------------------

###
POST http://localhost:3000/common-api/register
Content-Type: application/json

{
    "firstName":"Doe",
    "lastName":"John",
    "email":"doejohn@gmail.com",
    "password":"password123",
    "role":"author"
}

###
POST http://localhost:3000/common-api/login
Content-Type: application/json

{
    "email":"doejohn@gmail.com",
    "password":"password123"
}

###
POST http://localhost:3000/author-api/articles
Content-Type: application/json

{
    //authorId will be extracted from the token in the backend
    "author":"",
    "title":"My Second Article",
    "category":"Technology",
    "content":"This is the content of my second article."
}

###
GET http://localhost:3000/author-api/articles/myarticles

###
PUT http://localhost:3000/author-api/articles/69842dfa5db940c83c8a8487
Content-Type: application/json

{
    "title":"My Updated Article Title",
    "content":"This is the updated content of my article."
}

//--------------------AUTHOR API END--------------------

###
POST http://localhost:3000/common-api/login
Content-Type: application/json

{
    "email":"umesh@gmail.com",
    "password":"admin123"
}

###
GET http://localhost:3000/admin-api/articles

###
PUT http://localhost:3000/admin-api/users/698429fa4fa2e700bcba0a01
Content-Type: application/json

{
    "isActive": true
}

###
PUT http://localhost:3000/admin-api/articles/69842dfa5db940c83c8a8487
Content-Type: application/json

{
    "isArticleActive": true
}


//--------------------ADMIN API END--------------------

###
GET http://localhost:3000/common-api/logout

###
PUT http://localhost:3000/common-api/update-password
Content-Type: application/json

{
    "oldPassword": "newpassword456",
    "newPassword": "password123"
}

###
PUT http://localhost:3000/common-api/forgot-password
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "oldPassword": "newpassword456",
    "newPassword": "password123"
}